truyencuoi = [
    "> Bạn tù hỏi nhau:\n– Tại sao anh phải vào đây?\n– Tôi bỏ vợ…\n– Thế thôi sao? Chuyện nhỏ mà!\n– … từ trên lầu ba xuống.",
    "> Một vụ tai nạn giao thông vừa xảy ra ngoài phố. Mọi người tò mò chen lấn vòng trong vòng ngoài để xem. Một anh línhđến chậm không tài nào vào xem được. Tức quá, anh ta liền hét toáng lên:\n– Tôi là bố kẻ bị nạn đây!\nMọi người kinh ngạc quay lại nhìn và vội vã giãn ra cho anh ta vào. “Kẻ bị nạn” là một… chú chó vừa bị xe cán chết.",
    "> Chuyện kể rằng: Có một hồ nước thiêng ở Canada. Ai muốn ước gì cứ nói lời ước của mình rồi nhảy xuống hồ tắm là được toại nguyện. Thế là mọi người từ khắp nơi trên thế giới kéo nhau đến rất đông. Người thì ước thành gấu trắng, người thì muốn thành đại bàng và có người còn ước thành hoa anh đào nữa. Có một anh đến bên hồ, hấp tấp thế nào lại trượt chân, vội thốt lên “Oh,SHIT!” và … rơi tõm xuống hồ.",
    "> Chàng trai trở về nhà sau cuộc thi sát hạch lấy bằng lái xe với vẻ mặt hoang mang:\n– Thật là rắc rối – Anh ta nói với ông bố – Chiếc xe tải đó có vấn đề.\n– Nghĩa là con bị đánh trượt?\n– Điều đó chưa rõ. Cả Ban giám khảo có còn ai đâu ạ!",
    "> Một thanh niên tìm đến địa chỉ rao vặt “Cơ hội nghìn năm có một”, được diện kiến một nhân vật đầy ưu tư. Người ấy giải thích:\n– Công việc của anh sẽ là gánh vác mọi lo toan của tôi.\n– Việc này không dễ! Ông sẽ trả tôi baonhiêu?\n– 20.000 USD để làm mọi nỗi lo của tôi thành nỗilo của chính anh.\n– Tôi sẽ bắt đầu lo cho ông việc gì?\n– Kiếm 40.000 USD!",
    "> Một ông đang phóng xe trên đường thì thấy ngườiphụ nữ lái chiếc xe chạy ngược chiều hét to:\n– Heo!\n– Chó! – Ông này lập tức trả miếng.\nChưa kịp hả hê vì tài đối đáp nhanh của mình, xe của ông ta đâm sầm vào một con heo lớn nằm giữa đường.",
    "> Từ phòng xét nghiệm đi ra, bác sĩ nói với bệnh nhân:\n– Tôi có một tin tốt và tin xấu cho anh.\n– Cho tôi biết tin tốt trước – người ốm lạc quanđề nghị.\n– Tên của anh sẽ được người ta đặt cho một căn bệnh mới.",
    "> Trong quán rượu, một anh kể chuyện:\n– Này, người ta nói rằng diện tích trên mặt trăng đủ cho hàng triệu người sống đấy!\n– Đến ngày trăng khuyết thì lộn cổ cả nút!\n– Ừ nhỉ!",
    "> Tại trạm điện cao thế, chàng công nhân đang sửachữa trên nóc nói với anh đứng dưới đất:\n– Ê! Mày có thấy 4 sợi dây đang thòng xuốngkhông?\n– Thấy rồi!\n– Thấy rồi hả? Cầm lấy 2 sợi xem! Có thấy gìkhông?\n– Hai sợi này không có vấn đề gì.\n– Không sao hả? Tốt! Đừng đụng vào 2 sợi dây kianhé, điện cao thế sờ vào là cháy thành than đấy!",
    "> Thầy giáo nói với học sinh:\n– Em hãy mời ông của em đến gặp tôi!\n– Dạ, ý thầy muốn mời “ông bố” củaem?\n– Không, mời ông của em. Tôi muốn chỉ cho ông ấyxem con trai ông ấy đã phạm những lỗi gì trong vở bài tập về nhàcủa em.",

    "> Mom : Come down it’s dinner time.\nMe : In a few minutes.\nMom : NOW!!\nMe : Ok\n*downstairs*\nMe : Where’s dinner ?\nMom : It will be ready in 10 minutes!! ",
    "> Akpos goes to the post office, buys an envelope and screams out loud into it and then seals it.\nWhen the post office attendant asked him why he did that, he smiled and replied with a soft voice.\n“I’M SENDING A VOICE MAIL”",
    "> Father Wants To Go To Bed\nNext-door Neighbor’s Little Boy : “Father say could you lend him your cassette player for tonight ?”\nHeavy – Metal Enthusiast : “Have you a party on ?”\nLittle Boy : “Oh, no. Father only wants to go to bed “. ",
    "> Three guys stranded on a desert island find a magic lantern containing a genie, who grants them each one wish. The first guy wishes he was off the island and back home. The second guy wishes the same. The third guy says: 'I’m lonely. I wish my friends were back here.'",
    "> A young boy enters a barber shop and the barber whispers to his customer. 'This is the dumbest kid in the world. Watch while I prove it you.' The barber puts a dollar bill in one hand and two quarters in the other, then calls the boy over and asks, 'Which do you want, son?' The boy takes the quarters and leaves. 'What did I tell you?' said the barber. After, when the customer leaves, the man sees the young baby coming out of the ice cream store. He said, 'Hey, baby boy! Can I ask you a question? Why did you choose the quarter instead of the dollar bill?' The boy licked his cone and replied, 'Because the day I take the dollar, the game is over!'",
    "> A guy is sitting at home when he hears a knock at the door. He opens the door and sees a snail on the porch. He picks up the snail and throws it as far as he can. 3 years later, he heard a knock on the door againt. He opens the door and sees the snail. This snail says, 'What the hell was that all about?'.",
    "> Two campers are going through the woods when a black bear suddenly appears in the clearing in front of them about fifty meter. The bear sees the campers and begins to head toward them. The first guy drops his backpack, digs out a pair of sneakers, and frantically begins to put them on. The second guy says, 'What are you doing? Sneakers won’t help you outrun that bear.' 'I don’t need to outrun the bear,' the first guy says. 'I just need to outrun you.'",
    "> Three guys stranded on a desert island find a magic lantern containing a genie, who grants them each one wish. The first guy wishes he was off the island and come back home. The second guy wishes the same. The third guy says: 'I’m lonely. I wish tow friends were back here.'",
    "> 'Hey, how about the render- vous?”\n'It can be said that a half of success”\n'What do you mean?”\n'I came to the dated place but she didn’t.”",

]